package checkers.scenes.utils;

public enum SceneType
{
    MAIN_MENU,
    COOPERATION_INTRO,
    COOPERATION,
    MULTIPLAYER_INTRO,
    MULTIPLAYER_CREATE_GAME,
    MULTIPLAYER_JOIN_GAME,
    MULTIPLAYER_SERVER,
    MULTIPLAYER_CLIENT,
    SINGLEPLAYER_INTRO,
    SINGLEPLAYER,
    REPLAYS_INTRO
}
